name: Android Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get repository name
        id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore from secret
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > ./app/release.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK (Release)
        run: ./gradlew assembleRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          STORE_FILE: release.jks
          
      - name: Locate and rename generated APK
        id: find_apk
        run: |
          APK_PATH=$(find ./app -name "*.apk" | head -n 1)
          NEW_APK_PATH=./app/${{ steps.repository.outputs.name }}.${{ github.ref_name }}.apk
          mv "$APK_PATH" "$NEW_APK_PATH"
          echo "APK found at: $NEW_APK_PATH"
          echo "apk_path=$NEW_APK_PATH" >> $GITHUB_OUTPUT

      # Ensure workflow permissions: Settings > Actions > General > Workflow permissions: Read and write
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: APK ${{ github.ref_name }}
          files: ${{ steps.find_apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
